### ISSUE TITLE
Error: No enum constant jacusa.io.FileType.--VCF

### ISSUE THREAD

**Issue by XRCHAM** [dieterich-lab/JACUSA2#37]
Another error is when I tried to add E filter to get rid of dbsnp.vcf file like this way, I met error" No enum constant jacusa.io.FileType.--VCF" as below.

```
#!/bin/bash

export INP1=$1
export INP2=$2
export OUT=$3

#-RRDs------------
#CHANGE EDIT DISTANCE AGAIN
java -jar ~/bin/JACUSA_v2.0.0.jar call-2 -s -c 20 -P RF-FIRSTSTRAND -R genome.fa -p 16 -W 1000000 -filterNM_1 7 -filterNM_2 7  -T 1 -a E:file=snps.vcf:type:VCF -r ${OUT} ${INP1} ${INP2}
```

java.lang.IllegalArgumentException: No enum constant jacusa.io.FileType.--VCF
        at java.lang.Enum.valueOf(Enum.java:238)
        at jacusa.io.FileType.valueOf(FileType.java:1)
        at lib.cli.options.filter.FileTypeOption.process(FileTypeOption.java:25)
        at jacusa.filter.factory.FilterFactory.processCLI(FilterFactory.java:66)
        at jacusa.filter.factory.FilterFactory.processCLI(FilterFactory.java:51)
        at lib.cli.options.FilterConfigOption.process(FilterConfigOption.java:92)
        at lib.cli.CLI.processArgs(CLI.java:295)
        at lib.util.AbstractTool.run(AbstractTool.java:48)
        at jacusa.JACUSA.main(JACUSA.java:96)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
srun: error: midway2-bigmem04: task 0: Exited with exit code 1

**Comment by piechottam** [comment]
The format for Filtering is as follows:
-a <FILTER>:option1:option2=value
option1 is a flag - no specific value
option2 has a value.

Please change
"-a E:file=snps.vcf:type:VCF"
to
"-a E:file=snps.vcf:type=VCF"
and rerurn.

**Comment by XRCHAM** [comment]
After changing to "-a E:file=snps.vcf:type=VCF", new error pops up. And this error always raised whether I add -R genome.fa or not.

INFO   	00:00:00  Computing overlap between sequence records.
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.0-RC23 call-2 -s -c 20 -P RF-FIRSTSTRAND -R genome.fa -p 32 -W 1000000 -filterNM_1 7 -filterNM_2 7 -T 1 -a D,M,Y,E:file=snps.vcf:type=VCF -r XvsY.DP20.FULL X_1_dup.bam,X_2_dup.bam Y_1_dup.bam,Y_2_dup.bam
--------------------------------------------------------------------------------
java.lang.NullPointerException
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.init(FileBasedContainedCoordinate.java:114)
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.<init>(FileBasedContainedCoordinate.java:40)
	at jacusa.filter.ExcludeSiteFilter.<init>(ExcludeSiteFilter.java:28)
	at jacusa.filter.factory.ExcludeSiteFilterFactory.createFilter(ExcludeSiteFilterFactory.java:82)
	at jacusa.filter.factory.FilterFactory.registerFilter(FilterFactory.java:132)
	at jacusa.filter.FilterConfig.registerFilters(FilterConfig.java:64)
	at lib.util.ConditionContainer.initReplicateContainer(ConditionContainer.java:63)
	at lib.worker.AbstractWorker.<init>(AbstractWorker.java:64)
	at jacusa.worker.CallWorker.<init>(CallWorker.java:31)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:253)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:1)
	at lib.worker.WorkerDispatcher.createWorker(WorkerDispatcher.java:52)
	at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:78)
	at lib.util.AbstractTool.run(AbstractTool.java:60)
	at jacusa.JACUSA.main(JACUSA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
srun: error: midway2-bigmem01: task 0: Exited with exit code 1



INFO   	00:00:00  Computing overlap between sequence records.
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.0-RC23 call-2 -s -c 20 -P RF-FIRSTSTRAND -p 32 -W 1000000 -filterNM_1 7 -filterNM_2 7 -T 1 -a D,M,Y,E:file=snps.vcf:type=VCF -r XvsY.DP20.FULL X_1_dup.bam,X_2_dup.bam Y_1_dup.bam,Y_2_dup.bam
--------------------------------------------------------------------------------
java.lang.NullPointerException
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.init(FileBasedContainedCoordinate.java:114)
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.<init>(FileBasedContainedCoordinate.java:40)
	at jacusa.filter.ExcludeSiteFilter.<init>(ExcludeSiteFilter.java:28)
	at jacusa.filter.factory.ExcludeSiteFilterFactory.createFilter(ExcludeSiteFilterFactory.java:82)
	at jacusa.filter.factory.FilterFactory.registerFilter(FilterFactory.java:132)
	at jacusa.filter.FilterConfig.registerFilters(FilterConfig.java:64)
	at lib.util.ConditionContainer.initReplicateContainer(ConditionContainer.java:63)
	at lib.worker.AbstractWorker.<init>(AbstractWorker.java:64)
	at jacusa.worker.CallWorker.<init>(CallWorker.java:31)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:253)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:1)
	at lib.worker.WorkerDispatcher.createWorker(WorkerDispatcher.java:52)
	at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:78)
	at lib.util.AbstractTool.run(AbstractTool.java:60)
	at jacusa.JACUSA.main(JACUSA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
srun: error: midway2-bigmem01: task 0: Exited with exit code 1
