### ISSUE TITLE
Error with bed file and rt-arrest mode

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/JACUSA2#42]
Dear @piechottam ,

Call:
JACUSA2 Version: 2.0.0-RC22 call-2 -m 1 -A -b /prj/JACUSA2_TestField/Nanopore_HEK293/miCLIP2/union_flat.bed -q 1 -c 4 -p 10 -D -I -a D,Y -P1 FR-SECONDSTRAND -P2 FR-SECONDSTRAND -r MazF_vs_cond2_FTO_miCLIPsites_RC22_call2_result.out SRR8450805_STARmapping_uniq_rmdup.bam,SRR8450807_STARmapping_uniq_rmdup.bam,SRR8450809_STARmapping_uniq_rmdup.bam SRR8450806_STARmapping_uniq_rmdup.bam,SRR8450808_STARmapping_uniq_rmdup.bam,SRR8450810_STARmapping_uniq_rmdup.bam

java.lang.NullPointerException
        at lib.worker.WorkerDispatcher.hasNext(WorkerDispatcher.java:60)
        at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:64)
        at lib.util.AbstractTool.run(AbstractTool.java:60)
        at jacusa.JACUSA.main(JACUSA.java:96)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)

**Comment by CDieterich** [comment]
a cut -f1-3 seems to solve the issue.. but this is not nice at all.

**Comment by piechottam** [comment]
This has been fixed and will be available in the next release of JACUSA2.

As a temporary fix, please manually remove other columns inn BED file:
```
cut -f1-3 <BED> > <MODIFIED-BED>
```
