### ISSUE TITLE
filtering artifacts using -a E:filename

### ISSUE THREAD

**Issue by BreenMS** [dieterich-lab/JACUSA2#50]
Hi, 

We are using the -a E option to filter known SNPs based on a VCF file. In this example, the VCF file we are using for input was obtained UCSC, here: ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/

`00-common_all.vcf.gz`: Common human SNPs (minor allele frequency >= 0.01

We are running the following command: 

`java -jar $JACUSA2_JAR call-1 -r results.out Sample1.bam -p 10 -a D,M,Y,E:file=00-common_all.vcf:type=VCF -s -m 20 -R GRCh38.primary_assembly.genome.fa -P RF-FIRSTSTRAND`

and receiving the following error: 

```
java.lang.NullPointerException
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.init(FileBasedContainedCoordinate.java:114)
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.<init>(FileBasedContainedCoordinate.java:40)
	at jacusa.filter.ExcludeSiteFilter.<init>(ExcludeSiteFilter.java:28)
	at jacusa.filter.factory.ExcludeSiteFilterFactory.createFilter(ExcludeSiteFilterFactory.java:82)
	at jacusa.filter.factory.FilterFactory.registerFilter(FilterFactory.java:132)
	at jacusa.filter.FilterConfig.registerFilters(FilterConfig.java:64)
	at lib.util.ConditionContainer.initReplicateContainer(ConditionContainer.java:63)
	at lib.worker.AbstractWorker.<init>(AbstractWorker.java:64)
	at jacusa.worker.CallWorker.<init>(CallWorker.java:31)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:253)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:1)
	at lib.worker.WorkerDispatcher.createWorker(WorkerDispatcher.java:52)
	at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:78)
	at lib.util.AbstractTool.run(AbstractTool.java:60)
	at jacusa.JACUSA.main(JACUSA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
```
We have two questions: 

1. We are unsure what is causing this error, any chance you can advise on this one?
2. Are you able to provide a link that contains pre-built BED or VCF test files based on things folks would commonly want to filter (common SNPs, black listed regions of the genome, homopolymeric regions etc...).? A couple test examples/files might be useful. 

Thank you, 

M

**Comment by BreenMS** [comment]
Thank you for the reply and pointing out the codecs. 

1. Yes, vcf is unpacked and checked with vcftools. 
2. Yes, RNA editing sites. 
3. Our work around has been to convert the vcf to bed and filter post calling - which is working fine.

If we find the source of the original error, will circle back to this thread.
