### ISSUE TITLE
java issue with v2.0.1

### ISSUE THREAD

**Issue by joegeorgeson** [dieterich-lab/JACUSA2#57]
Dear JACUSA2 team,

I am able to use `v2.0.0-S-BETA-1` but `v2.0.1` gives me the below error (using jre/8.121). Can you advise?

```
INFO   	00:00:00  Computing overlap between sequence records.
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.1 pileup -c 9 -q 20 -m 0 -P RF-FIRSTSTRAND -F 3844 -R hg19.fa -r out.jacusa in.bam
--------------------------------------------------------------------------------
INFO   	00:00:00  Thread 1: Working on contig chr1:10001-110000
java.lang.NullPointerException
	at lib.data.DefaultDataContainer.merge(DefaultDataContainer.java:180)
	at lib.data.DefaultDataContainer.merge(DefaultDataContainer.java:1)
	at lib.data.ParallelData.merge(ParallelData.java:134)
	at lib.data.ParallelData.getCombPooledData(ParallelData.java:80)
	at jacusa.method.rtarrest.CoverageStatistic.calculate(CoverageStatistic.java:21)
	at lib.stat.AbstractStat.filter(AbstractStat.java:16)
	at jacusa.worker.PileupWorker.process(PileupWorker.java:48)
	at lib.worker.AbstractWorker.doWork(AbstractWorker.java:139)
	at lib.worker.AbstractWorker.processReady(AbstractWorker.java:197)
	at lib.worker.AbstractWorker.run(AbstractWorker.java:213)
```

**Comment by piechottam** [comment]
Does the problem persist if you run?
`... pileup -c 9 -q 20 -m 0 -P RF-FIRSTSTRAND -F 3844 -R hg19.fa -r out.jacusa in.bam in.bam`

**Comment by joegeorgeson** [comment]
> Does the problem persist if you run?
> `... pileup -c 9 -q 20 -m 0 -P RF-FIRSTSTRAND -F 3844 -R hg19.fa -r out.jacusa in.bam in.bam`

That fixed it! I'm a bit confused, could I have found this in the documentation?

**Comment by piechottam** [comment]
You found a bug. JACUSA2 should work with only 1x (condition)  "... in.bam". I'll fix it - thank you for your feedback!

**Comment by joegeorgeson** [comment]
Thank you very much for the help!!!
