### ISSUE TITLE
Unknown output format: /

### ISSUE THREAD

**Issue by CelineLabbeCurie** [dieterich-lab/JACUSA2#63]
Hello,

I'm trying to use Jacusa2 for the first time but I have an error. Maybe it's just something wrong in my command line and I just don't see it but any help would be appreciated : 

```
java -jar JACUSA_v2.0.1.jar call-1 -a E:file=/myPath/snpHG38/00-All.vcf:type=VCF -s -f /myPath/Human/hg38/genome/hg38.fa -B C2T -r /myPath/jacusa2/outputJacusa2.txt /myPath/sample_Aligned.sortedByCoord.out.bam

java.lang.IllegalArgumentException: Unknown output format: /
	at lib.cli.options.ResultFormatOption.process(ResultFormatOption.java:59)
	at lib.cli.CLI.processArgs(CLI.java:295)
	at lib.util.AbstractTool.run(AbstractTool.java:48)
	at jacusa.JACUSA.main(JACUSA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)

```
I don't see what could be wrong with the -r argument...
Thanks for your help.
Best,

**Comment by piechottam** [comment]
In your call, please change to -f [...] to -R [...].

usage: JACUSA call-1 [OPTIONS] BAM1_1[,BAM1_2,...]
[...]
 -f <OUTPUT-FORMAT>    Choose output format:
                       <*> B: BED6-extended result format
                       < > V: VCF Output format. Option -P will be ignored (VCF is unstranded)
-R <REF-FASTA>        use reference FASTA file (must be indexed)
[...]

**Comment by CelineLabbeCurie** [comment]
Thanks ! I don't have this error anymore. Now I have this : 

```
java.lang.NullPointerException
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.init(FileBasedContainedCoordinate.java:114)
	at jacusa.filter.factory.exclude.FileBasedContainedCoordinate.<init>(FileBasedContainedCoordinate.java:40)
	at jacusa.filter.ExcludeSiteFilter.<init>(ExcludeSiteFilter.java:28)
	at jacusa.filter.factory.ExcludeSiteFilterFactory.createFilter(ExcludeSiteFilterFactory.java:82)
	at jacusa.filter.factory.FilterFactory.registerFilter(FilterFactory.java:132)
	at jacusa.filter.FilterConfig.registerFilters(FilterConfig.java:64)
	at lib.util.ConditionContainer.initReplicateContainer(ConditionContainer.java:63)
	at lib.worker.AbstractWorker.<init>(AbstractWorker.java:64)
	at jacusa.worker.CallWorker.<init>(CallWorker.java:31)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:253)
	at jacusa.method.call.CallMethod.createWorker(CallMethod.java:1)
	at lib.worker.WorkerDispatcher.createWorker(WorkerDispatcher.java:52)
	at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:78)
	at lib.util.AbstractTool.run(AbstractTool.java:60)
	at jacusa.JACUSA.main(JACUSA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
```

Any idea wich file I should check or change as it's not specified please ?
Best,

**Comment by piechottam** [comment]
It is the ExcludeSite Filter -> I have to check if this is a bug.
Might ask you for some data.

As a workaround I would run the analysis without the Exclude Filter and use bedtools to remove unwanted sites.

**Comment by CelineLabbeCurie** [comment]
Thanks a lot, it's working ! Maybe there's a problem with my vcf file. I'll try to download it again to check.

**Comment by CelineLabbeCurie** [comment]
I was thinking that maybe the error was due to different origine of :
- the fast file hg38.fa (given to me but the name suggest it comes from UCSC) used to align to the genome and then given as an argument to Jacusa 
and
- the vcf file probably coming for NCBI and not UCSC so maybe the coordinate aren't exactly the same or the way of naming the chromosomes are not the same...

Best,
