### ISSUE TITLE
Problems writing file with multithreading

### ISSUE THREAD

**Issue by Izar-de-villasante** [dieterich-lab/JACUSA2#65]
When jacusa2 ends calling and has to merge it fails. Usually it just gets stacked and the job keeps on running but las time I got this error:

INFO    00:03:31  Thread 51: Working on contig chrY:59301874-59373565
java.lang.NullPointerException: Cannot invoke "java.io.BufferedWriter.write(String)" because "this.bw" is null
        at lib.io.AbstractResultFileWriter.writeLine(AbstractResultFileWriter.java:32)
        at lib.io.BEDlikeResultFileWriter.writeHeader(BEDlikeResultFileWriter.java:44)
        at lib.worker.WorkerDispatcher.writeOutput(WorkerDispatcher.java:124)
        at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:98)
        at lib.util.AbstractTool.run(AbstractTool.java:60)
        at jacusa.JACUSA.main(JACUSA.java:96)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
I was reading this thread and maybe it is related:
https://es.stackoverflow.com/questions/432241/exception-in-thread-main-java-lang-nullpointerexception-cannot-invoke-alumno

**Comment by piechottam** [comment]
Can you please provide your JACUSA2 call?
