### ISSUE TITLE
JACUSA_v2.0.4.jar pileup problem

### ISSUE THREAD

**Issue by dingtiany** [dieterich-lab/JACUSA2#81]
hello, I am using the JACUSA2 to find mismatch  under some treatment. So I use 'java -jar ~/software/jacusa/JACUSA_v2.0.4.jar pileup -r test_file a1.bam b1.bam -R Arabidopsis_thaliana.TAIR10.dna.toplevel.fa -p 4', but some error comes.  The environment is java 1.8 and JACUSA_v2.0.4
the error show like this: 
INFO    00:02:59  Thread 3: Working on contig 1:13100044-13200043
INFO    00:02:59  Thread 4: Working on contig 1:13200044-13300043
INFO    00:03:00  Thread 3: Working on contig 1:13300044-13400043
INFO    00:03:02  Thread 4: Working on contig 1:13400044-13500043
INFO    00:03:02  Thread 3: Working on contig 1:13500044-13600043
java.lang.IllegalArgumentException: Byte 89 unknown
        at lib.util.Base.valueOf(Base.java:74)
        at lib.data.storage.container.FileReferenceProvider.getReferenceBase(FileReferenceProvider.java:90)
        at lib.data.storage.container.FileReferenceProvider.getReferenceBase(FileReferenceProvider.java:68)
        at lib.data.assembler.DataAssembler.createDefaultDataContainer(DataAssembler.java:50)
        at lib.data.assembler.DataAssembler.assembleData(DataAssembler.java:39)
        at lib.util.ReplicateContainer.getDefaultDataContainer(ReplicateContainer.java:69)
        at lib.util.ConditionContainer.getDefaultDataContainer(ConditionContainer.java:46)
        at jacusa.worker.PileupWorker.createParallelData(PileupWorker.java:39)
        at lib.worker.AbstractWorker.hasNext(AbstractWorker.java:111)
        at lib.worker.AbstractWorker.processReady(AbstractWorker.java:196)
        at lib.worker.AbstractWorker.run(AbstractWorker.java:213)

I've tried several ways but none of them worked. could you give me some advice. 
Thanks for your help.
Best.

**Comment by piechottam** [comment]
Dear User,U have ambigious bases in your pileup y is c or t.Currently, we only support acgtn.
-------- Ursprüngliche Nachricht --------Von: dingtiany ***@***.***> Datum: 30.12.24  06:48  (GMT-06:00) An: dieterich-lab/JACUSA2 ***@***.***> Cc: Subscribed ***@***.***> Betreff: [dieterich-lab/JACUSA2] ACUSA_v2.0.4.jar pileup problem (Issue #81) 
hello, I am using the JACUSA2 to find mismatch  under some treatment. So I use 'java -jar ~/software/jacusa/JACUSA_v2.0.4.jar pileup -r test_file a1.bam b1.bam -R Arabidopsis_thaliana.TAIR10.dna.toplevel.fa -p 4', but some error comes.  The environment is java 1.8 and JACUSA_v2.0.4
the error show like this:
INFO    00:02:59  Thread 3: Working on contig 1:13100044-13200043
INFO    00:02:59  Thread 4: Working on contig 1:13200044-13300043
INFO    00:03:00  Thread 3: Working on contig 1:13300044-13400043
INFO    00:03:02  Thread 4: Working on contig 1:13400044-13500043
INFO    00:03:02  Thread 3: Working on contig 1:13500044-13600043
java.lang.IllegalArgumentException: Byte 89 unknown
at lib.util.Base.valueOf(Base.java:74)
at lib.data.storage.container.FileReferenceProvider.getReferenceBase(FileReferenceProvider.java:90)
at lib.data.storage.container.FileReferenceProvider.getReferenceBase(FileReferenceProvider.java:68)
at lib.data.assembler.DataAssembler.createDefaultDataContainer(DataAssembler.java:50)
at lib.data.assembler.DataAssembler.assembleData(DataAssembler.java:39)
at lib.util.ReplicateContainer.getDefaultDataContainer(ReplicateContainer.java:69)
at lib.util.ConditionContainer.getDefaultDataContainer(ConditionContainer.java:46)
at jacusa.worker.PileupWorker.createParallelData(PileupWorker.java:39)
at lib.worker.AbstractWorker.hasNext(AbstractWorker.java:111)
at lib.worker.AbstractWorker.processReady(AbstractWorker.java:196)
at lib.worker.AbstractWorker.run(AbstractWorker.java:213)
I've tried several ways but none of them worked. could you give me some advice.
Thanks for your help.
Best.

**Comment by dingtiany** [comment]
Thank you for your quick reply. So this error means bam file's some problem or JACUSA set's problem.  And I would like to ask you to provide some specific details about how I can solve it. 
Thanks again.

**Comment by dingtiany** [comment]
oh! I know the problem! Thank you again! You are right, my reference genome appears some not ATGCN bases.
Thank again for your quick reply.

**Comment by piechottam** [comment]
We are planning to support IUPAC codes in reference.

While the SAM/BAM file format supports IUPAC codes in sequence, we will not support this because our variant calling algorithm requires ACGT.

However, you could mask non ACTGN in your BAM file as "N"s.

**Comment by dingtiany** [comment]
And when try use one bam file to SNV detect, it come some error like:'java.lang.NullPointerException: Cannot invoke "lib.data.DataContainer.getUnstrandedRefBase()" because "provider" is null
        at lib.data.DefaultDataContainer.merge(DefaultDataContainer.java:180)
        at lib.data.DefaultDataContainer.merge(DefaultDataContainer.java:1)'
but when I  use >1 sample bam files, there is not error any more.
the code:'java -jar ~/software/jacusa/JACUSA_v2.0.4.jar pileup -r test_file -R cleaned.fa -p 6 -s sample.bam'
